version: '3.8'

services:
  mongo:
    image: bitnami/mongodb:6.0.6
    container_name: mongo
    restart: always
    tty: true
    environment:
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=logbook
      - MONGODB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'
    networks:
      - logbook

networks:
  logbook:
    driver: bridge
